//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByAeroBeHero {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByAeroBeHero.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced Params 的本地化字符串。
        /// </summary>
        public static string AdvancedParams {
            get {
                return ResourceManager.GetString("AdvancedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要上传？ 的本地化字符串。
        /// </summary>
        public static string AreYouSureYouWantToUpload {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto WP 的本地化字符串。
        /// </summary>
        public static string AutoWP {
            get {
                return ResourceManager.GetString("AutoWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速度计故障 的本地化字符串。
        /// </summary>
        public static string BadAccelHealth {
            get {
                return ResourceManager.GetString("BadAccelHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AHRS故障 的本地化字符串。
        /// </summary>
        public static string BadAHRS {
            get {
                return ResourceManager.GetString("BadAHRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气压计故障 的本地化字符串。
        /// </summary>
        public static string BadBaroHealth {
            get {
                return ResourceManager.GetString("BadBaroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罗盘故障 的本地化字符串。
        /// </summary>
        public static string BadCompassHealth {
            get {
                return ResourceManager.GetString("BadCompassHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误经纬度 的本地化字符串。
        /// </summary>
        public static string BadCoords {
            get {
                return ResourceManager.GetString("BadCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GPS 故障 的本地化字符串。
        /// </summary>
        public static string BadGPSHealth {
            get {
                return ResourceManager.GetString("BadGPSHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陀螺故障 的本地化字符串。
        /// </summary>
        public static string BadGyroHealth {
            get {
                return ResourceManager.GetString("BadGyroHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷达故障 的本地化字符串。
        /// </summary>
        public static string BadLiDARHealth {
            get {
                return ResourceManager.GetString("BadLiDARHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光流故障 的本地化字符串。
        /// </summary>
        public static string BadOptFlowHealth {
            get {
                return ResourceManager.GetString("BadOptFlowHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有地形数据 的本地化字符串。
        /// </summary>
        public static string BadorNoTerrainData {
            get {
                return ResourceManager.GetString("BadorNoTerrainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本调谐 的本地化字符串。
        /// </summary>
        public static string BasicTuning {
            get {
                return ResourceManager.GetString("BasicTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公开测试 的本地化字符串。
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These are beta firmware, use at your own risk!!! 的本地化字符串。
        /// </summary>
        public static string BetaWarning {
            get {
                return ResourceManager.GetString("BetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接到串口和检测板类型 的本地化字符串。
        /// </summary>
        public static string CanNotConnectToComPortAnd {
            get {
                return ResourceManager.GetString("CanNotConnectToComPortAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能绘制这个字段 的本地化字符串。
        /// </summary>
        public static string CannotGraphField {
            get {
                return ResourceManager.GetString("CannotGraphField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法检测到您的版本。请检查您的布线 的本地化字符串。
        /// </summary>
        public static string CantDetectBoardVersion {
            get {
                return ResourceManager.GetString("CantDetectBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查端口设置或使用端口？ 的本地化字符串。
        /// </summary>
        public static string CheckPortSettingsOr {
            get {
                return ResourceManager.GetString("CheckPortSettingsOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击完成 的本地化字符串。
        /// </summary>
        public static string Click_when_Done {
            get {
                return ResourceManager.GetString("Click_when_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令未能执行
        /// 的本地化字符串。
        /// </summary>
        public static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信错误-没有连接 的本地化字符串。
        /// </summary>
        public static string CommunicationErrorNoConnection {
            get {
                return ResourceManager.GetString("CommunicationErrorNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罗盘方差 的本地化字符串。
        /// </summary>
        public static string compass_variance {
            get {
                return ResourceManager.GetString("compass_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string CONNECTc {
            get {
                return ResourceManager.GetString("CONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        public static string ConnectFailed {
            get {
                return ResourceManager.GetString("ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在链接串口 的本地化字符串。
        /// </summary>
        public static string ConnectingMavlink {
            get {
                return ResourceManager.GetString("ConnectingMavlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择机架类型 的本地化字符串。
        /// </summary>
        public static string CopterTypeSelected {
            get {
                return ResourceManager.GetString("CopterTypeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择机架类型失败 的本地化字符串。
        /// </summary>
        public static string CopterTypeSetFailed {
            get {
                return ResourceManager.GetString("CopterTypeSetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择机架类型成功 的本地化字符串。
        /// </summary>
        public static string CopterTypeSetSuccessed {
            get {
                return ResourceManager.GetString("CopterTypeSetSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述:  的本地化字符串。
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到 的本地化字符串。
        /// </summary>
        public static string DetectedA {
            get {
                return ResourceManager.GetString("DetectedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测版本 的本地化字符串。
        /// </summary>
        public static string DetectingBoardVersion {
            get {
                return ResourceManager.GetString("DetectingBoardVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开 的本地化字符串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开 的本地化字符串。
        /// </summary>
        public static string DISCONNECTc {
            get {
                return ResourceManager.GetString("DISCONNECTc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从互联网下载 的本地化字符串。
        /// </summary>
        public static string DownloadedFromInternet {
            get {
                return ResourceManager.GetString("DownloadedFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从互联网下载 的本地化字符串。
        /// </summary>
        public static string DownloadingFromInternet {
            get {
                return ResourceManager.GetString("DownloadingFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确保你的桨不在飞机上 的本地化字符串。
        /// </summary>
        public static string EnsurePropsNotOn {
            get {
                return ResourceManager.GetString("EnsurePropsNotOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPPROM改变，你所有的设置将在更新过程中丢失，你想继续吗？ 的本地化字符串。
        /// </summary>
        public static string EppromChanged {
            get {
                return ResourceManager.GetString("EppromChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPPROM格式改变（{ 0）VS { 1 }） 的本地化字符串。
        /// </summary>
        public static string EppromFormatChanged {
            get {
                return ResourceManager.GetString("EppromFormatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定错误 的本地化字符串。
        /// </summary>
        public static string Error_binding {
            get {
                return ResourceManager.GetString("Error_binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭日志文件时出错 的本地化字符串。
        /// </summary>
        public static string ErrorClosingLogFile {
            get {
                return ResourceManager.GetString("ErrorClosingLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与自动驾驶仪通信时出错 的本地化字符串。
        /// </summary>
        public static string ErrorCommunicating {
            get {
                return ResourceManager.GetString("ErrorCommunicating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接错误
        /// 的本地化字符串。
        /// </summary>
        public static string ErrorConnecting {
            get {
                return ResourceManager.GetString("ErrorConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此功能在您的固件中没有启用 的本地化字符串。
        /// </summary>
        public static string ErrorFeatureNotEnabled {
            get {
                return ResourceManager.GetString("ErrorFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误加载固件文件 的本地化字符串。
        /// </summary>
        public static string ErrorFirmwareFile {
            get {
                return ResourceManager.GetString("ErrorFirmwareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收日志列表的错误 的本地化字符串。
        /// </summary>
        public static string ErrorLogList {
            get {
                return ResourceManager.GetString("ErrorLogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法从飞行器收到响应 的本地化字符串。
        /// </summary>
        public static string ErrorNoResponce {
            get {
                return ResourceManager.GetString("ErrorNoResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有连接。 的本地化字符串。
        /// </summary>
        public static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收列表错误
        /// 的本地化字符串。
        /// </summary>
        public static string ErrorReceivingParams {
            get {
                return ResourceManager.GetString("ErrorReceivingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令拒绝了MAV 的本地化字符串。
        /// </summary>
        public static string ErrorRejectedByMAV {
            get {
                return ResourceManager.GetString("ErrorRejectedByMAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误重命名文件 的本地化字符串。
        /// </summary>
        public static string ErrorRenameFile {
            get {
                return ResourceManager.GetString("ErrorRenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设定参数  的本地化字符串。
        /// </summary>
        public static string ErrorSettingParameter {
            get {
                return ResourceManager.GetString("ErrorSettingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置{ 0 }失败 的本地化字符串。
        /// </summary>
        public static string ErrorSetValueFailed {
            get {
                return ResourceManager.GetString("ErrorSetValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传固件错误 的本地化字符串。
        /// </summary>
        public static string ErrorUploadingFirmware {
            get {
                return ResourceManager.GetString("ErrorUploadingFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展调谐 的本地化字符串。
        /// </summary>
        public static string ExtendedTuning {
            get {
                return ResourceManager.GetString("ExtendedTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日志失败-不会登录这个会话 的本地化字符串。
        /// </summary>
        public static string Failclog {
            get {
                return ResourceManager.GetString("Failclog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败 的本地化字符串。
        /// </summary>
        public static string FailedDownload {
            get {
                return ResourceManager.GetString("FailedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取失败 的本地化字符串。
        /// </summary>
        public static string FailedReadHEX {
            get {
                return ResourceManager.GetString("FailedReadHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read firmware.hex : 的本地化字符串。
        /// </summary>
        public static string FailedToReadHex {
            get {
                return ResourceManager.GetString("FailedToReadHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败 的本地化字符串。
        /// </summary>
        public static string FailedUpload {
            get {
                return ResourceManager.GetString("FailedUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FailSafe 的本地化字符串。
        /// </summary>
        public static string FailSafe {
            get {
                return ResourceManager.GetString("FailSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flight Modes 的本地化字符串。
        /// </summary>
        public static string FlightModes {
            get {
                return ResourceManager.GetString("FlightModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Parameter List 的本地化字符串。
        /// </summary>
        public static string FullParameterList {
            get {
                return ResourceManager.GetString("FullParameterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Parameter Tree 的本地化字符串。
        /// </summary>
        public static string FullParameterTree {
            get {
                return ResourceManager.GetString("FullParameterTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GeoFence 的本地化字符串。
        /// </summary>
        public static string GeoFence {
            get {
                return ResourceManager.GetString("GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出区域 的本地化字符串。
        /// </summary>
        public static string GeofenceBreach {
            get {
                return ResourceManager.GetString("GeofenceBreach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting  的本地化字符串。
        /// </summary>
        public static string Getting {
            get {
                return ResourceManager.GetString("Getting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW List 的本地化字符串。
        /// </summary>
        public static string GettingFWList {
            get {
                return ResourceManager.GetString("GettingFWList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting FW Version 的本地化字符串。
        /// </summary>
        public static string GettingFWVersion {
            get {
                return ResourceManager.GetString("GettingFWVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Params 的本地化字符串。
        /// </summary>
        public static string GettingParams {
            get {
                return ResourceManager.GetString("GettingParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Params... 的本地化字符串。
        /// </summary>
        public static string GettingParamsD {
            get {
                return ResourceManager.GetString("GettingParamsD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting updated parameters 的本地化字符串。
        /// </summary>
        public static string GettingUpdatedParams {
            get {
                return ResourceManager.GetString("GettingUpdatedParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Got param  的本地化字符串。
        /// </summary>
        public static string Gotparam {
            get {
                return ResourceManager.GetString("Gotparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效高度 的本地化字符串。
        /// </summary>
        public static string InvalidAlt {
            get {
                return ResourceManager.GetString("InvalidAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效波特率 的本地化字符串。
        /// </summary>
        public static string InvalidBaudRate {
            get {
                return ResourceManager.GetString("InvalidBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的板类型 的本地化字符串。
        /// </summary>
        public static string InvalidBoardType {
            get {
                return ResourceManager.GetString("InvalidBoardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的证书 的本地化字符串。
        /// </summary>
        public static string InvalidCert {
            get {
                return ResourceManager.GetString("InvalidCert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效字段 的本地化字符串。
        /// </summary>
        public static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的文件名 的本地化字符串。
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入的号码无效
        /// 的本地化字符串。
        /// </summary>
        public static string InvalidNumberEntered {
            get {
                return ResourceManager.GetString("InvalidNumberEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效平移范围 的本地化字符串。
        /// </summary>
        public static string InvalidPanRange {
            get {
                return ResourceManager.GetString("InvalidPanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效端口名 的本地化字符串。
        /// </summary>
        public static string InvalidPortName {
            get {
                return ResourceManager.GetString("InvalidPortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效倾斜范围 的本地化字符串。
        /// </summary>
        public static string InvalidTiltRange {
            get {
                return ResourceManager.GetString("InvalidTiltRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效更新率 的本地化字符串。
        /// </summary>
        public static string InvalidUpdateRate {
            get {
                return ResourceManager.GetString("InvalidUpdateRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Stats 的本地化字符串。
        /// </summary>
        public static string LinkStats {
            get {
                return ResourceManager.GetString("LinkStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please click ok and move the autopilot around all axises in a circular motion 的本地化字符串。
        /// </summary>
        public static string MagCalibMsg {
            get {
                return ResourceManager.GetString("MagCalibMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mavlink Connecting... 的本地化字符串。
        /// </summary>
        public static string MavlinkConnecting {
            get {
                return ResourceManager.GetString("MavlinkConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are missing data points. do you want to run the calibration anyway? 的本地化字符串。
        /// </summary>
        public static string MissingDataPoints {
            get {
                return ResourceManager.GetString("MissingDataPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Firmware 的本地化字符串。
        /// </summary>
        public static string NewFirmware {
            get {
                return ResourceManager.GetString("NewFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New firmware available
        /// 的本地化字符串。
        /// </summary>
        public static string NewFirmwareA {
            get {
                return ResourceManager.GetString("NewFirmwareA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No FMT message for  的本地化字符串。
        /// </summary>
        public static string NoFMTMessage {
            get {
                return ResourceManager.GetString("NoFMTMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No need to upload. already on the board 的本地化字符串。
        /// </summary>
        public static string NoNeedToUpload {
            get {
                return ResourceManager.GetString("NoNeedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NO RC Receiver 的本地化字符串。
        /// </summary>
        public static string NORCReceiver {
            get {
                return ResourceManager.GetString("NORCReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note 的本地化字符串。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Obtain From Module 的本地化字符串。
        /// </summary>
        public static string ObtainFromModule {
            get {
                return ResourceManager.GetString("ObtainFromModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only 1 Heatbeat Received 的本地化字符串。
        /// </summary>
        public static string Only1Hb {
            get {
                return ResourceManager.GetString("Only1Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only 1 Mavlink Heartbeat Packets was read from this port - Verify your hardware is setup correctly
        ///Mission Planner waits for 2 valid heartbeat packets before connecting 的本地化字符串。
        /// </summary>
        public static string Only1HbD {
            get {
                return ResourceManager.GetString("Only1HbD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect first 的本地化字符串。
        /// </summary>
        public static string PleaseConnect {
            get {
                return ResourceManager.GetString("PleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please connect and backup your config in the configuration tab. 的本地化字符串。
        /// </summary>
        public static string PleaseConnectAndBackupConfig {
            get {
                return ResourceManager.GetString("PleaseConnectAndBackupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please load a valid file 的本地化字符串。
        /// </summary>
        public static string PleaseLoadValidFile {
            get {
                return ResourceManager.GetString("PleaseLoadValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a cell first 的本地化字符串。
        /// </summary>
        public static string PleaseSelectCell {
            get {
                return ResourceManager.GetString("PleaseSelectCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please unplug the board, and then press OK and plug back in.
        ///Mission Planner will look for 30 seconds to find the board 的本地化字符串。
        /// </summary>
        public static string PleaseUnplugTheBoardAnd {
            get {
                return ResourceManager.GetString("PleaseUnplugTheBoardAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Please upgrade 的本地化字符串。
        /// </summary>
        public static string Pleaseup {
            get {
                return ResourceManager.GetString("Pleaseup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait for the musical tones to finish before clicking OK 的本地化字符串。
        /// </summary>
        public static string PleaseWaitForTheMusicalTones {
            get {
                return ResourceManager.GetString("PleaseWaitForTheMusicalTones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pos horiz variance 的本地化字符串。
        /// </summary>
        public static string pos_horiz_variance {
            get {
                return ResourceManager.GetString("pos_horiz_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pos vert variance 的本地化字符串。
        /// </summary>
        public static string pos_vert_variance {
            get {
                return ResourceManager.GetString("pos_vert_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sucessfully programmed 的本地化字符串。
        /// </summary>
        public static string ProgrammedOK {
            get {
                return ResourceManager.GetString("ProgrammedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Put the transmitter in bind mode. Receiver is waiting. 的本地化字符串。
        /// </summary>
        public static string Put_the_transmitter_in_bind_mode__Receiver_is_waiting {
            get {
                return ResourceManager.GetString("Put_the_transmitter_in_bind_mode__Receiver_is_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ? 的本地化字符串。
        /// </summary>
        public static string QuestionMark {
            get {
                return ResourceManager.GetString("QuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw Param Warning 的本地化字符串。
        /// </summary>
        public static string RawParamWarning {
            get {
                return ResourceManager.GetString("RawParamWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All values on this screen are not min/max checked. Please double check your input.
        ///Please use Standard/Advanced Params for the safe settings 的本地化字符串。
        /// </summary>
        public static string RawParamWarningi {
            get {
                return ResourceManager.GetString("RawParamWarningi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex 的本地化字符串。
        /// </summary>
        public static string ReadingHex {
            get {
                return ResourceManager.GetString("ReadingHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reading Hex File 的本地化字符串。
        /// </summary>
        public static string ReadingHexFile {
            get {
                return ResourceManager.GetString("ReadingHexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received List 的本地化字符串。
        /// </summary>
        public static string ReceivedList {
            get {
                return ResourceManager.GetString("ReceivedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 run anyway 的本地化字符串。
        /// </summary>
        public static string RunAnyway {
            get {
                return ResourceManager.GetString("RunAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving 的本地化字符串。
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a comport 的本地化字符串。
        /// </summary>
        public static string SelectComport {
            get {
                return ResourceManager.GetString("SelectComport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Here 的本地化字符串。
        /// </summary>
        public static string SetHere {
            get {
                return ResourceManager.GetString("SetHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show me again? 的本地化字符串。
        /// </summary>
        public static string ShowMeAgain {
            get {
                return ResourceManager.GetString("ShowMeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standard Params 的本地化字符串。
        /// </summary>
        public static string StandardParams {
            get {
                return ResourceManager.GetString("StandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your model is still moving are you sure you want to disconnect? 的本地化字符串。
        /// </summary>
        public static string Stillmoving {
            get {
                return ResourceManager.GetString("Stillmoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 terrain alt variance 的本地化字符串。
        /// </summary>
        public static string terrain_alt_variance {
            get {
                return ResourceManager.GetString("terrain_alt_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This board has been retired, Mission Planner this will upload the last available version to your board 的本地化字符串。
        /// </summary>
        public static string ThisBoardHasBeenRetired {
            get {
                return ResourceManager.GetString("ThisBoardHasBeenRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout waiting for autoscan/no mavlink device connected 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracker Home 的本地化字符串。
        /// </summary>
        public static string TrackerHome {
            get {
                return ResourceManager.GetString("TrackerHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 trunk 的本地化字符串。
        /// </summary>
        public static string Trunk {
            get {
                return ResourceManager.GetString("Trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These are the latest trunk firmware, use at your own risk!!! 的本地化字符串。
        /// </summary>
        public static string TrunkWarning {
            get {
                return ResourceManager.GetString("TrunkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trying to connect.
        ///Timeout in {0} 的本地化字符串。
        /// </summary>
        public static string Trying {
            get {
                return ResourceManager.GetString("Trying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Units: {0}{1} 的本地化字符串。
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Found
        ///
        ///Do you wish to update now? [link; 的本地化字符串。
        /// </summary>
        public static string UpdateFound {
            get {
                return ResourceManager.GetString("UpdateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Now 的本地化字符串。
        /// </summary>
        public static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload Complete 的本地化字符串。
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading {0} bytes to Board: 的本地化字符串。
        /// </summary>
        public static string UploadingBytesToBoard {
            get {
                return ResourceManager.GetString("UploadingBytesToBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload succeeded, but verify failed: exp {0} got {1} at  的本地化字符串。
        /// </summary>
        public static string UploadSucceededButVerifyFailed {
            get {
                return ResourceManager.GetString("UploadSucceededButVerifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 速度方差 的本地化字符串。
        /// </summary>
        public static string velocity_variance {
            get {
                return ResourceManager.GetString("velocity_variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证完成 的本地化字符串。
        /// </summary>
        public static string VerifyComplete {
            get {
                return ResourceManager.GetString("VerifyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证固件 的本地化字符串。
        /// </summary>
        public static string VerifyFirmware {
            get {
                return ResourceManager.GetString("VerifyFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning, as of AC 3.1 motors will spin when armed, configurable through the MOT_SPIN_ARMED parameter 的本地化字符串。
        /// </summary>
        public static string WarningAC31 {
            get {
                return ResourceManager.GetString("WarningAC31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning, if you are installing AC 3.2 for the first time you MUST redo a Compass calibration. 的本地化字符串。
        /// </summary>
        public static string WarningAC32 {
            get {
                return ResourceManager.GetString("WarningAC32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Browse will not function correctly without FMT messages in your log.
        ///These appear to be missing from your log. 的本地化字符串。
        /// </summary>
        public static string WarningLogBrowseFMTMissing {
            get {
                return ResourceManager.GetString("WarningLogBrowseFMTMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning rally points are located greater than RALLY_LIMIT_KM 的本地化字符串。
        /// </summary>
        public static string Warningrallypointdistance {
            get {
                return ResourceManager.GetString("Warningrallypointdistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Params
        ///DON&apos;T DO THIS IF YOU ARE IN THE AIR
        /// 的本地化字符串。
        /// </summary>
        public static string WarningUpdateParamList {
            get {
                return ResourceManager.GetString("WarningUpdateParamList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are using unsupported hardware.
        ///This board does not contain a valid certificate of authenticity.
        ///Please contact your hardware vendor about signing your hardware. 的本地化字符串。
        /// </summary>
        public static string YouAreUsingUnsupportedHardware {
            get {
                return ResourceManager.GetString("YouAreUsingUnsupportedHardware", resourceCulture);
            }
        }
    }
}
